### ISSUE TITLE
Example .env values?

### ISSUE THREAD

**Issue by norton120** [crflynn/sqlalchemy-databricks#9]
This is always a weirdly painful thing with Sqlalchemy dialects and seems like such a simple thing to make easier. 
I have yet to find 2 dialects that expect params like host/cluster/role/compute_warehouse in _exactly_ the same format. If you were to provide dummy values of each in the `.env` file it would probably save millions of quietly lost person-hours trying to decipher things like "does this dialect want the host escaped? where does it want the account id, as a get value in the string or a conn param? what have I done with my life that I am re-running tests at 3am because I don't know if this conn string wants protocol prefixes?!?!?" and such. 

Also once/if I figure it out I'm happy to make a PR with the examples

**Comment by susodapop** [comment]
I opened a PR adding this information. Feel free to ping me if you have questions.
